version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mqtt-broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mosquitto_data:/mosquitto/data
      - mosquitto_logs:/mosquitto/log
    restart: unless-stopped
    networks:
      - iot-network

  alarm-service:
    build: .
    container_name: iot-alarm-service
    depends_on:
      - mosquitto
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./config:/app/config
    environment:
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
    restart: unless-stopped
    networks:
      - iot-network

  data-simulator:
    build: .
    container_name: data-simulator
    depends_on:
      - mosquitto
    command: python data_simulate.py
    environment:
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
    restart: unless-stopped
    networks:
      - iot-network

volumes:
  mosquitto_data:
  mosquitto_logs:

networks:
  iot-network:
    driver: bridge